secret:
  enable-builtin-rules:
    - aws-access-key-id
    - aws-secret-access-key
  disable-allow-rules:
    - slack-access-token
    - slack-web-hook

#  disable-rules:
 #   - slack-access-token
  #  - slack-web-hook
  #disable-allow-rules:
   # - markdown
