name: Gitleaks Secret Scan

on:
  pull_request:
    branches:
      - main 
      - actionstest
      - Test111 # or your default branch

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks to scan for secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-format sarif --report-path gitleaks-report.sarif

      - name: Upload Gitleaks SARIF Report (Optional for GitHub Security tab)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: gitleaks-report.sarif
