name: Trivy Secrets Scan

on:
  push:
    branches:
    - main
    - trivy
    - actionstest
  pull_request:
    branches:
    - main
    - trivy
    - actionstest

jobs:
  trivy-secrets-scan:
    name: Scan repo for exposed secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Trivy Secret Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          scanners: secret
          format: table
          severity: CRITICAL,HIGH
