name: CI - TruffleHog Secret Scan

on:
  push:
    branches:
      - main
      - trufflehog
      - actiontest
  pull_request:
    branches:
      - main
      - trufflehog
      - actiontest

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog secret scan
        uses: trufflesecurity/trufflehog@main
        with:
          scanArguments: --only-verified
