name: GitGuardian Secret Scan

on:
  pull_request:
    branches:
      - main  # or change to your default branch

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitGuardian CLI
        run: |
          pip install ggshield

      - name: Run secret scan with GitGuardian
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        run: |
          echo "Scanning repository for secrets..."
          ggshield secret scan repo . --exit-zero-on-scan-error

      - name: Fail if secrets found
        if: failure()
        run: |
          echo "❌ Secret(s) detected by GitGuardian. Failing the PR."
          exit 1
