name: CI - TruffleHog Secret Scan

on:
  push:
    branches:
      - main
      - trufflehog
      - actiontest
  pull_request:
    branches:
      - main
      - trufflehog
      - actiontest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
- name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog on full git history
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔍 Running TruffleHog on repository history..."
          trufflehog git https://github.com/${{ github.repository }} \
            --branch ${{ github.ref_name }} \
            --json > trufflehog-results.json

      - name: Show and fail on secrets
        run: |
          if [ -s trufflehog-results.json ]; then
            echo "❌ Secrets detected!"
            cat trufflehog-results.json
            exit 1
          else
            echo "✅ No secrets found."
          fi

      - name: Upload TruffleHog Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-results.json
