name: CI - Secret Scan

on:
  push:
    branches:
      - main
      - gitleaks
  pull_request:
    branches:
      - main
      - gitleaks

jobs:
  secret-scan:
    name: Checkout and Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .github/gitleaks.toml  # optional: use your custom config
  #      env:
  #        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # optional, if needed for private repos
