# Copyright © 2022 Gitleaks LLC - All Rights Reserved.
# You may use this code under the terms of the GITLEAKS-ACTION END-USER LICENSE AGREEMENT.
# You should have received a copy of the GITLEAKS-ACTION END-USER LICENSE AGREEMENT with this file.
# If not, please visit https://github.com/gitleaks/gitleaks-action/blob/main/COMMERCIAL-LICENSE.txt.

# CAUTION: This is for testing purposes.
name: gitleaks-action-HEAD

on:
  pull_request:
    branches:
      - actionstest
      - main
      - gitleaks

  push:
    branches:
      - actionstest
      - main
      - gitleaks

  workflow_dispatch:

jobs:
  scan:
    name: gitleaks-action-HEAD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gitleaks

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
