name: CI - TruffleHog Secret Scan

on:
  push:
    branches:
      - main
      - trufflehog
      - actiontest
  pull_request:
    branches:
      - main
      - trufflehog
      - actiontest
      - trufflehog111

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: reviewdog
          steps:
            # ...
            - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
              with:
                reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
            - name: Run reviewdog
              env:
                REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                reviewdog -reporter=github-pr-check -runners=golint,govet
                # or
                reviewdog -reporter=github-pr-review -runners=golint,govet
