name: CI - TruffleHog Secret Scan

on:
  push:
    branches:
      - main
      - trufflehog
      - actiontest
  pull_request:
    branches:
      - main
      - trufflehog
      - actiontest

jobs:
  trufflehog-scan:
    name: Run TruffleHog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - Confirm Git Repo
        run: |
          git status

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install TruffleHog
        run: pip install trufflehog
      
      - name: Run TruffleHog scan
        run: |
          trufflehog git --repo_path . --json > trufflehog-results.json
          if [ -s trufflehog-results.json ]; then
            echo "❌ Potential secrets found!"
            cat trufflehog-results.json
            exit 1
          else
            echo "✅ No secrets found."
          fi

